FROM node:10 AS builder
RUN \
    apt-get update && apt-get upgrade -q -y && \
    apt-get install -y ca-certificates git node-gyp make

# declare args paras  get from docker-compose
ARG CHAIN_NAME
ARG CHAIN_TYPE
ARG NODE_RPC_URL

# set env when build image
ENV CHAIN_NAME $CHAIN_NAME
ENV CHAIN_TYPE $CHAIN_TYPE
ENV NODE_RPC_URL $NODE_RPC_URL

WORKDIR /root/expedition

# Cache npm install
COPY package*.json ./
RUN npm install
COPY . .
RUN  chmod +x ./set_default_chain.sh && \
     ./set_default_chain.sh && \ 
    npx browserslist@latest --update-db &&\
    npm install && \
    npm run build

# Build static assets
#RUN npm run build

# STEP 2 build a small nginx image with static website
FROM nginx:alpine

# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# Copy static assets to nginx image
COPY --from=builder /root/expedition/build/ /usr/share/nginx/html
#EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
