version: "3.6"
services:
  expedition:
    container_name: expedition_container
    image: duonghuynhbaocr/expedition-local-nginx:0.0.1
    ports:
      - 3000:3000 # expose tcp by default
    ulimits:
      nofile:
        soft: 2048
        hard: 4096
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf #Add a volume to mount nginx.conf file to the container to replace the default file with the one created.
    restart: unless-stopped